export enum ActionTypes {
  AUTHENTICATE = "AUTHENTICATE",
  AUTHENTICATE_CHECK = "AUTHENTICATE_CHECK",
  AUTHENTICATE_SUCCESS = "AUTHENTICATE_SUCCESS",
  AUTHENTICATE_FAILURE = "AUTHENTICATE_FAILURE",
  LOGOUT = "LOGOUT",
  LOGOUT_SUCCESS = "LOGOUT_SUCCESS",
  LOGOUT_FAILURE = "LOGOUT_FAILURE",

  SET_CURRENT_REQUEST = "SET_CURRENT_REQUEST",
  SET_CURRENT_RESPONSE = "SET_CURRENT_RESPONSE",
  SET_HAS_REQUEST_SYNTAX_ERROR = "SET_HAS_REQUEST_SYNTAX_ERROR",
  SEND_REQUEST = "SEND_REQUEST",
  ADD_REQUEST_TO_HISTORY = "ADD_REQUEST_TO_HISTORY",
  CLEAR_REQUESTS = "CLEAR_REQUESTS",
}